// Package pg provides implementations of pdax domain repository interfaces.
package pg

// Schema contains sql commands for setup database.
// Schema includes extensions and tables which must be created before working with
// the storage.
const Schema = `
CREATE TABLE trade (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    currency_pair text NOT NULL,
    price numeric NOT NULL,
    quantity numeric NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE order_book (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
	order_book jsonb
);
`
