version: '3.9'
services:
  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pdax_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
